sudo: false
language: node_js
env:
- CXX="g++-4.8"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8
node_js:
- '9'
- '8'
- '6'
script:
- istanbul cover ./node_modules/.bin/grunt --report lcovonly && istanbul report text  && ( cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js || true  ) && rm -rf coverage
before_script:
- npm install -g istanbul
- npm install coveralls
notifications:
  hipchat:
    rooms:
      secure: ZSzRIsLD9EBX6QPGnNogHuwqHKjpU/XFZrjEk+rQ5C4YU1r67em+PGTlNOZvStYuYIxS9oFXaw4+0ZYEZ5dcHGpWhD7teiPX3WWrmo88URZRi/3/Gk2Zmhj6vGK4CR6G32n4u/3trM8uYLJxGI1iWgtzF4Jn5NTjLeVTEWiy40eN1mTMY+pfRgjBJvuP/Ebl8kLwyZs/6jDVQXLFE/JA6VK8Z7y3yNrp+6/eV5WME7tIpI252OcT/v6xqMH2Xe1GzWC0bN1ju3UBN409t/9zYerifxPOH4AnUxjtDZQfqQVTv7352SQepoJ5UKaoAH+2xQA6z3DeCT2c7HGCsOkV5nlE5PyaAyOmamYNsgf5ypas7hC40zOSiAqzytSjfZbC3qvOp3EOLvByc1t9woWxYfy1x9Xc0WwZQrMMd+1QwnbECUr55YNPLDRbnM/+i4PU5kAodmbmQoiNsuBTEzHg+hMpaUOZDj0slDlZZWwuMhlVdF/J+WQ/zqbQk6bFc4JkRJzD1pPsDaV84Yqv5gcA6kZAR7dmnSa5FY+tIPZ43HiMZlIXhh5w/RgKzmpS2hGs4cOdoQfVuq1uFTq/NnNipUzdeQBElvVc89f2EDumQVCWfgjtgMfNXqm3lo5Up7JTL7kq72qEuUlY8yXjqAP3iXFQ/7g3Q6SaexTjVaEPb+4=
